name: opa_policy_list_action
author: Simon Duff
description: Action to apply every policy in a policies.hcl file and summarise the results

inputs:
  timeout:
    description: How long to allow each policy to run
    required: false
  policies_file:
    description: File containing the policy list
    required: false
  input_file:
    description: Input file to check policies against
    required: false
  opa_binary:
    description: Location of the opa binary
    required: false
  show_all:
    description: Show all policy results, not just failures
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: List files in checkout
      run: ls -alR /home/runner/
      shell: bash
    - name: Run Policy Checks
      run: python opa_policy_list_action.py
      shell: bash
      with:
        path: .

branding:
  color: blue
  icon: check-square
